package acr

// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

import (
    "github.com/Azure/go-autorest/autorest"
)

// The package's fully qualified name.
const fqdn = "users/t-gigo/go/src/github.com/azurecr/acr-cli/acr"

            // CancelBlobUploadBadRequestResponse ...
            type CancelBlobUploadBadRequestResponse struct {
            Data *Error `json:"data,omitempty"`
            }

            // CancelBlobUploadNotFoundResponse ...
            type CancelBlobUploadNotFoundResponse struct {
            Data *Error `json:"data,omitempty"`
            }

            // CancelBlobUploadUnauthorizedResponse ...
            type CancelBlobUploadUnauthorizedResponse struct {
            Data *Error `json:"data,omitempty"`
            }

            // CheckDockerRegistryV2SupportUnauthorizedResponse ...
            type CheckDockerRegistryV2SupportUnauthorizedResponse struct {
            autorest.Response `json:"-"`
            Data *Error `json:"data,omitempty"`
            }

            // DeleteManifestBadRequestResponse ...
            type DeleteManifestBadRequestResponse struct {
            Data *Error `json:"data,omitempty"`
            }

            // DeleteManifestMetadataBadRequestResponse ...
            type DeleteManifestMetadataBadRequestResponse struct {
            Data *Error `json:"data,omitempty"`
            }

            // DeleteManifestMetadataNotFoundResponse ...
            type DeleteManifestMetadataNotFoundResponse struct {
            Data *Error `json:"data,omitempty"`
            }

            // DeleteManifestMetadataUnauthorizedResponse ...
            type DeleteManifestMetadataUnauthorizedResponse struct {
            Data *Error `json:"data,omitempty"`
            }

            // DeleteManifestNotFoundResponse ...
            type DeleteManifestNotFoundResponse struct {
            Data *Error `json:"data,omitempty"`
            }

            // DeleteManifestUnauthorizedResponse ...
            type DeleteManifestUnauthorizedResponse struct {
            Data *Error `json:"data,omitempty"`
            }

            // DeleteRepositoryBadRequestResponse ...
            type DeleteRepositoryBadRequestResponse struct {
            Data *Error `json:"data,omitempty"`
            }

            // DeleteRepositoryMetadataBadRequestResponse ...
            type DeleteRepositoryMetadataBadRequestResponse struct {
            Data *Error `json:"data,omitempty"`
            }

            // DeleteRepositoryMetadataNotFoundResponse ...
            type DeleteRepositoryMetadataNotFoundResponse struct {
            Data *Error `json:"data,omitempty"`
            }

            // DeleteRepositoryMetadataUnauthorizedResponse ...
            type DeleteRepositoryMetadataUnauthorizedResponse struct {
            Data *Error `json:"data,omitempty"`
            }

            // DeleteRepositoryNotFoundResponse ...
            type DeleteRepositoryNotFoundResponse struct {
            Data *Error `json:"data,omitempty"`
            }

            // DeleteRepositoryUnauthorizedResponse ...
            type DeleteRepositoryUnauthorizedResponse struct {
            Data *Error `json:"data,omitempty"`
            }

            // DeleteTagBadRequestResponse ...
            type DeleteTagBadRequestResponse struct {
            Data *Error `json:"data,omitempty"`
            }

            // DeleteTagMetadataBadRequestResponse ...
            type DeleteTagMetadataBadRequestResponse struct {
            Data *Error `json:"data,omitempty"`
            }

            // DeleteTagMetadataNotFoundResponse ...
            type DeleteTagMetadataNotFoundResponse struct {
            Data *Error `json:"data,omitempty"`
            }

            // DeleteTagMetadataUnauthorizedResponse ...
            type DeleteTagMetadataUnauthorizedResponse struct {
            Data *Error `json:"data,omitempty"`
            }

            // DeleteTagNotFoundResponse ...
            type DeleteTagNotFoundResponse struct {
            Data *Error `json:"data,omitempty"`
            }

            // DeleteTagUnauthorizedResponse ...
            type DeleteTagUnauthorizedResponse struct {
            Data *Error `json:"data,omitempty"`
            }

            // EndBlobUploadBadRequestResponse ...
            type EndBlobUploadBadRequestResponse struct {
            Data *Error `json:"data,omitempty"`
            }

            // EndBlobUploadNotFoundResponse ...
            type EndBlobUploadNotFoundResponse struct {
            Data *Error `json:"data,omitempty"`
            }

            // EndBlobUploadUnauthorizedResponse ...
            type EndBlobUploadUnauthorizedResponse struct {
            Data *Error `json:"data,omitempty"`
            }

            // Error ...
            type Error struct {
            Errors *[]ErrorErrorsItem `json:"errors,omitempty"`
            }

            // ErrorErrorsItem ...
            type ErrorErrorsItem struct {
            Code *string `json:"code,omitempty"`
            Message *string `json:"message,omitempty"`
            Detail *string `json:"detail,omitempty"`
            }

            // GetBlobBadRequestResponse ...
            type GetBlobBadRequestResponse struct {
            Data *Error `json:"data,omitempty"`
            }

            // GetBlobNotFoundResponse ...
            type GetBlobNotFoundResponse struct {
            Data *Error `json:"data,omitempty"`
            }

            // GetBlobUnauthorizedResponse ...
            type GetBlobUnauthorizedResponse struct {
            Data *Error `json:"data,omitempty"`
            }

            // GetBlobUploadStatusBadRequestResponse ...
            type GetBlobUploadStatusBadRequestResponse struct {
            Data *Error `json:"data,omitempty"`
            }

            // GetBlobUploadStatusNotFoundResponse ...
            type GetBlobUploadStatusNotFoundResponse struct {
            Data *Error `json:"data,omitempty"`
            }

            // GetBlobUploadStatusUnauthorizedResponse ...
            type GetBlobUploadStatusUnauthorizedResponse struct {
            Data *Error `json:"data,omitempty"`
            }

            // GetManifestAttributesBadRequestResponse ...
            type GetManifestAttributesBadRequestResponse struct {
            Data *Error `json:"data,omitempty"`
            }

            // GetManifestAttributesNotFoundResponse ...
            type GetManifestAttributesNotFoundResponse struct {
            Data *Error `json:"data,omitempty"`
            }

            // GetManifestAttributesOKResponse ...
            type GetManifestAttributesOKResponse struct {
            Data *ManifestAttributes `json:"data,omitempty"`
            }

            // GetManifestAttributesUnauthorizedResponse ...
            type GetManifestAttributesUnauthorizedResponse struct {
            Data *Error `json:"data,omitempty"`
            }

            // GetManifestBadRequestResponse ...
            type GetManifestBadRequestResponse struct {
            Data *Error `json:"data,omitempty"`
            }

            // GetManifestMetadataBadRequestResponse ...
            type GetManifestMetadataBadRequestResponse struct {
            Data *Error `json:"data,omitempty"`
            }

            // GetManifestMetadataNotFoundResponse ...
            type GetManifestMetadataNotFoundResponse struct {
            Data *Error `json:"data,omitempty"`
            }

            // GetManifestMetadataUnauthorizedResponse ...
            type GetManifestMetadataUnauthorizedResponse struct {
            Data *Error `json:"data,omitempty"`
            }

            // GetManifestNotFoundResponse ...
            type GetManifestNotFoundResponse struct {
            Data *Error `json:"data,omitempty"`
            }

            // GetManifestOKResponse ...
            type GetManifestOKResponse struct {
            Data *Layers `json:"data,omitempty"`
            }

            // GetManifestUnauthorizedResponse ...
            type GetManifestUnauthorizedResponse struct {
            Data *Error `json:"data,omitempty"`
            }

            // GetRepositoryAttributesBadRequestResponse ...
            type GetRepositoryAttributesBadRequestResponse struct {
            Data *Error `json:"data,omitempty"`
            }

            // GetRepositoryAttributesNotFoundResponse ...
            type GetRepositoryAttributesNotFoundResponse struct {
            Data *Error `json:"data,omitempty"`
            }

            // GetRepositoryAttributesOKResponse ...
            type GetRepositoryAttributesOKResponse struct {
            Data *RepositoryAttributes `json:"data,omitempty"`
            }

            // GetRepositoryAttributesUnauthorizedResponse ...
            type GetRepositoryAttributesUnauthorizedResponse struct {
            Data *Error `json:"data,omitempty"`
            }

            // GetRepositoryMetadataBadRequestResponse ...
            type GetRepositoryMetadataBadRequestResponse struct {
            Data *Error `json:"data,omitempty"`
            }

            // GetRepositoryMetadataNotFoundResponse ...
            type GetRepositoryMetadataNotFoundResponse struct {
            Data *Error `json:"data,omitempty"`
            }

            // GetRepositoryMetadataUnauthorizedResponse ...
            type GetRepositoryMetadataUnauthorizedResponse struct {
            Data *Error `json:"data,omitempty"`
            }

            // GetTagAttributesBadRequestResponse ...
            type GetTagAttributesBadRequestResponse struct {
            Data *Error `json:"data,omitempty"`
            }

            // GetTagAttributesNotFoundResponse ...
            type GetTagAttributesNotFoundResponse struct {
            Data *Error `json:"data,omitempty"`
            }

            // GetTagAttributesOKResponse ...
            type GetTagAttributesOKResponse struct {
            Data *TagAttributes `json:"data,omitempty"`
            }

            // GetTagAttributesUnauthorizedResponse ...
            type GetTagAttributesUnauthorizedResponse struct {
            Data *Error `json:"data,omitempty"`
            }

            // GetTagMetadataBadRequestResponse ...
            type GetTagMetadataBadRequestResponse struct {
            Data *Error `json:"data,omitempty"`
            }

            // GetTagMetadataNotFoundResponse ...
            type GetTagMetadataNotFoundResponse struct {
            Data *Error `json:"data,omitempty"`
            }

            // GetTagMetadataUnauthorizedResponse ...
            type GetTagMetadataUnauthorizedResponse struct {
            Data *Error `json:"data,omitempty"`
            }

            // Layers ...
            type Layers struct {
            Name *string `json:"name,omitempty"`
            Tag *string `json:"tag,omitempty"`
            FsLayers *[]LayersFsLayersItem `json:"fsLayers,omitempty"`
            History *string `json:"history,omitempty"`
            Signature *string `json:"signature,omitempty"`
            }

            // LayersFsLayersItem ...
            type LayersFsLayersItem struct {
            BlobSum *string `json:"blobSum,omitempty"`
            }

            // ListManifestMetadataBadRequestResponse ...
            type ListManifestMetadataBadRequestResponse struct {
            Data *Error `json:"data,omitempty"`
            }

            // ListManifestMetadataNotFoundResponse ...
            type ListManifestMetadataNotFoundResponse struct {
            Data *Error `json:"data,omitempty"`
            }

            // ListManifestMetadataOKResponse ...
            type ListManifestMetadataOKResponse struct {
            Data *ManifestMetadataList `json:"data,omitempty"`
            }

            // ListManifestMetadataUnauthorizedResponse ...
            type ListManifestMetadataUnauthorizedResponse struct {
            Data *Error `json:"data,omitempty"`
            }

            // ListManifestsBadRequestResponse ...
            type ListManifestsBadRequestResponse struct {
            Data *Error `json:"data,omitempty"`
            }

            // ListManifestsNotFoundResponse ...
            type ListManifestsNotFoundResponse struct {
            Data *Error `json:"data,omitempty"`
            }

            // ListManifestsOKResponse ...
            type ListManifestsOKResponse struct {
            Data *ManifestAttributeList `json:"data,omitempty"`
            }

            // ListManifestsUnauthorizedResponse ...
            type ListManifestsUnauthorizedResponse struct {
            Data *Error `json:"data,omitempty"`
            }

            // ListRepositoriesBadRequestResponse ...
            type ListRepositoriesBadRequestResponse struct {
            Data *Error `json:"data,omitempty"`
            }

            // ListRepositoriesBadRequestResponseType ...
            type ListRepositoriesBadRequestResponseType struct {
            Data *Error `json:"data,omitempty"`
            }

            // ListRepositoriesOKResponse ...
            type ListRepositoriesOKResponse struct {
            Data *[]string `json:"data,omitempty"`
            }

            // ListRepositoriesOKResponseType ...
            type ListRepositoriesOKResponseType struct {
            Data *[]string `json:"data,omitempty"`
            }

            // ListRepositoriesUnauthorizedResponse ...
            type ListRepositoriesUnauthorizedResponse struct {
            Data *Error `json:"data,omitempty"`
            }

            // ListRepositoriesUnauthorizedResponseType ...
            type ListRepositoriesUnauthorizedResponseType struct {
            Data *Error `json:"data,omitempty"`
            }

            // ListRepositoryMetadataBadRequestResponse ...
            type ListRepositoryMetadataBadRequestResponse struct {
            Data *Error `json:"data,omitempty"`
            }

            // ListRepositoryMetadataNotFoundResponse ...
            type ListRepositoryMetadataNotFoundResponse struct {
            Data *Error `json:"data,omitempty"`
            }

            // ListRepositoryMetadataOKResponse ...
            type ListRepositoryMetadataOKResponse struct {
            Data *RepositoryMetadata `json:"data,omitempty"`
            }

            // ListRepositoryMetadataUnauthorizedResponse ...
            type ListRepositoryMetadataUnauthorizedResponse struct {
            Data *Error `json:"data,omitempty"`
            }

            // ListTagMetadataBadRequestResponse ...
            type ListTagMetadataBadRequestResponse struct {
            Data *Error `json:"data,omitempty"`
            }

            // ListTagMetadataNotFoundResponse ...
            type ListTagMetadataNotFoundResponse struct {
            Data *Error `json:"data,omitempty"`
            }

            // ListTagMetadataOKResponse ...
            type ListTagMetadataOKResponse struct {
            Data *TagMetadataList `json:"data,omitempty"`
            }

            // ListTagMetadataUnauthorizedResponse ...
            type ListTagMetadataUnauthorizedResponse struct {
            Data *Error `json:"data,omitempty"`
            }

            // ListTagsBadRequestResponse ...
            type ListTagsBadRequestResponse struct {
            Data *Error `json:"data,omitempty"`
            }

            // ListTagsNotFoundResponse ...
            type ListTagsNotFoundResponse struct {
            Data *Error `json:"data,omitempty"`
            }

            // ListTagsNotFoundResponseType ...
            type ListTagsNotFoundResponseType struct {
            Data *Error `json:"data,omitempty"`
            }

            // ListTagsOKResponse ...
            type ListTagsOKResponse struct {
            Name *string `json:"name,omitempty"`
            Tags *[]string `json:"tags,omitempty"`
            }

            // ListTagsOKResponseType ...
            type ListTagsOKResponseType struct {
            Data *TagAttributeList `json:"data,omitempty"`
            }

            // ListTagsUnauthorizedResponse ...
            type ListTagsUnauthorizedResponse struct {
            Data *Error `json:"data,omitempty"`
            }

            // ListTagsUnauthorizedResponseType ...
            type ListTagsUnauthorizedResponseType struct {
            Data *Error `json:"data,omitempty"`
            }

            // ManifestAttributeList ...
            type ManifestAttributeList struct {
            Registry *string `json:"registry,omitempty"`
            ImageName *string `json:"imageName,omitempty"`
            Manifests *[]ManifestAttributesBase `json:"manifests,omitempty"`
            }

            // ManifestAttributes ...
            type ManifestAttributes struct {
            Registry *string `json:"registry,omitempty"`
            ImageName *string `json:"imageName,omitempty"`
            Manifest *ManifestAttributesManifest `json:"manifest,omitempty"`
            }

            // ManifestAttributesBase ...
            type ManifestAttributesBase struct {
            Digest *string `json:"digest,omitempty"`
            CreatedTime *string `json:"createdTime,omitempty"`
            LastUpdateTime *string `json:"lastUpdateTime,omitempty"`
            Architecture *string `json:"architecture,omitempty"`
            Os *string `json:"os,omitempty"`
            MediaType *string `json:"mediaType,omitempty"`
            Tags *[]string `json:"tags,omitempty"`
            ChangeableAttributes *ManifestAttributesBaseChangeableAttributes `json:"changeableAttributes,omitempty"`
            }

            // ManifestAttributesBaseChangeableAttributes ...
            type ManifestAttributesBaseChangeableAttributes struct {
            DeleteEnabled *bool `json:"deleteEnabled,omitempty"`
            WriteEnabled *bool `json:"writeEnabled,omitempty"`
            ListEnabled *bool `json:"listEnabled,omitempty"`
            ReadEnabled *bool `json:"readEnabled,omitempty"`
            QuarantineState *string `json:"quarantineState,omitempty"`
            QuarantineDetails *string `json:"quarantineDetails,omitempty"`
            }

            // ManifestAttributesManifest ...
            type ManifestAttributesManifest struct {
            References *[]ManifestAttributesManifestReferencesItem `json:"references,omitempty"`
            QuarantineTag *string `json:"quarantineTag,omitempty"`
            Digest *string `json:"digest,omitempty"`
            CreatedTime *string `json:"createdTime,omitempty"`
            LastUpdateTime *string `json:"lastUpdateTime,omitempty"`
            Architecture *string `json:"architecture,omitempty"`
            Os *string `json:"os,omitempty"`
            MediaType *string `json:"mediaType,omitempty"`
            Tags *[]string `json:"tags,omitempty"`
            ChangeableAttributes *ManifestAttributesBaseChangeableAttributes `json:"changeableAttributes,omitempty"`
            }

            // ManifestAttributesManifestReferencesItem ...
            type ManifestAttributesManifestReferencesItem struct {
            Digest *string `json:"digest,omitempty"`
            Architecture *string `json:"architecture,omitempty"`
            Os *string `json:"os,omitempty"`
            }

            // ManifestMetadataList ...
            type ManifestMetadataList struct {
            Registry *string `json:"registry,omitempty"`
            ImageName *string `json:"imageName,omitempty"`
            Digest *string `json:"digest,omitempty"`
            Metadata *[]string `json:"metadata,omitempty"`
            }

            // RepositoryAttributes ...
            type RepositoryAttributes struct {
            Registry *string `json:"registry,omitempty"`
            ImageName *string `json:"imageName,omitempty"`
            CreatedTime *string `json:"createdTime,omitempty"`
            LastUpdateTime *string `json:"lastUpdateTime,omitempty"`
            ManifestCount *float64 `json:"manifestCount,omitempty"`
            TagCount *float64 `json:"tagCount,omitempty"`
            ChangeableAttributes *RepositoryAttributesChangeableAttributes `json:"changeableAttributes,omitempty"`
            }

            // RepositoryAttributesChangeableAttributes ...
            type RepositoryAttributesChangeableAttributes struct {
            DeleteEnabled *bool `json:"deleteEnabled,omitempty"`
            WriteEnabled *bool `json:"writeEnabled,omitempty"`
            ListEnabled *bool `json:"listEnabled,omitempty"`
            ReadEnabled *bool `json:"readEnabled,omitempty"`
            }

            // RepositoryMetadata ...
            type RepositoryMetadata struct {
            Registry *string `json:"registry,omitempty"`
            ImageName *string `json:"imageName,omitempty"`
            Metadata *[]string `json:"metadata,omitempty"`
            }

            // SetObject ...
            type SetObject struct {
            autorest.Response `json:"-"`
            Value interface{} `json:"value,omitempty"`
            }

            // StartBlobUploadBadRequestResponse ...
            type StartBlobUploadBadRequestResponse struct {
            Data *Error `json:"data,omitempty"`
            }

            // StartBlobUploadUnauthorizedResponse ...
            type StartBlobUploadUnauthorizedResponse struct {
            Data *Error `json:"data,omitempty"`
            }

            // TagAttributeList ...
            type TagAttributeList struct {
            Registry *string `json:"registry,omitempty"`
            ImageName *string `json:"imageName,omitempty"`
            Tags *[]TagAttributesBase `json:"tags,omitempty"`
            }

            // TagAttributes ...
            type TagAttributes struct {
            Registry *string `json:"registry,omitempty"`
            ImageName *string `json:"imageName,omitempty"`
            Tag *TagAttributesTag `json:"tag,omitempty"`
            }

            // TagAttributesBase ...
            type TagAttributesBase struct {
            Name *string `json:"name,omitempty"`
            Digest *string `json:"digest,omitempty"`
            CreatedTime *string `json:"createdTime,omitempty"`
            LastUpdateTime *string `json:"lastUpdateTime,omitempty"`
            Signed *bool `json:"signed,omitempty"`
            QuarantineState *string `json:"quarantineState,omitempty"`
            ChangeableAttributes *TagAttributesBaseChangeableAttributes `json:"changeableAttributes,omitempty"`
            }

            // TagAttributesBaseChangeableAttributes ...
            type TagAttributesBaseChangeableAttributes struct {
            DeleteEnabled *bool `json:"deleteEnabled,omitempty"`
            WriteEnabled *bool `json:"writeEnabled,omitempty"`
            ListEnabled *bool `json:"listEnabled,omitempty"`
            ReadEnabled *bool `json:"readEnabled,omitempty"`
            }

            // TagAttributesTag ...
            type TagAttributesTag struct {
            SignatureRecord *string `json:"signatureRecord,omitempty"`
            Name *string `json:"name,omitempty"`
            Digest *string `json:"digest,omitempty"`
            CreatedTime *string `json:"createdTime,omitempty"`
            LastUpdateTime *string `json:"lastUpdateTime,omitempty"`
            Signed *bool `json:"signed,omitempty"`
            QuarantineState *string `json:"quarantineState,omitempty"`
            ChangeableAttributes *TagAttributesBaseChangeableAttributes `json:"changeableAttributes,omitempty"`
            }

            // TagMetadataList ...
            type TagMetadataList struct {
            Registry *string `json:"registry,omitempty"`
            ImageName *string `json:"imageName,omitempty"`
            TagName *string `json:"tagName,omitempty"`
            Metadata *[]string `json:"metadata,omitempty"`
            }

            // UpdateManifestAttributesBadRequestResponse ...
            type UpdateManifestAttributesBadRequestResponse struct {
            Data *Error `json:"data,omitempty"`
            }

            // UpdateManifestAttributesNotFoundResponse ...
            type UpdateManifestAttributesNotFoundResponse struct {
            Data *Error `json:"data,omitempty"`
            }

            // UpdateManifestAttributesUnauthorizedResponse ...
            type UpdateManifestAttributesUnauthorizedResponse struct {
            Data *Error `json:"data,omitempty"`
            }

            // UpdateManifestMetadataBadRequestResponse ...
            type UpdateManifestMetadataBadRequestResponse struct {
            Data *Error `json:"data,omitempty"`
            }

            // UpdateManifestMetadataNotFoundResponse ...
            type UpdateManifestMetadataNotFoundResponse struct {
            Data *Error `json:"data,omitempty"`
            }

            // UpdateManifestMetadataUnauthorizedResponse ...
            type UpdateManifestMetadataUnauthorizedResponse struct {
            Data *Error `json:"data,omitempty"`
            }

            // UpdateRepositoryAttributesBadRequestResponse ...
            type UpdateRepositoryAttributesBadRequestResponse struct {
            Data *Error `json:"data,omitempty"`
            }

            // UpdateRepositoryAttributesNotFoundResponse ...
            type UpdateRepositoryAttributesNotFoundResponse struct {
            Data *Error `json:"data,omitempty"`
            }

            // UpdateRepositoryAttributesUnauthorizedResponse ...
            type UpdateRepositoryAttributesUnauthorizedResponse struct {
            Data *Error `json:"data,omitempty"`
            }

            // UpdateRepositoryMetadataBadRequestResponse ...
            type UpdateRepositoryMetadataBadRequestResponse struct {
            Data *Error `json:"data,omitempty"`
            }

            // UpdateRepositoryMetadataNotFoundResponse ...
            type UpdateRepositoryMetadataNotFoundResponse struct {
            Data *Error `json:"data,omitempty"`
            }

            // UpdateRepositoryMetadataUnauthorizedResponse ...
            type UpdateRepositoryMetadataUnauthorizedResponse struct {
            Data *Error `json:"data,omitempty"`
            }

            // UpdateTagAttributesBadRequestResponse ...
            type UpdateTagAttributesBadRequestResponse struct {
            Data *Error `json:"data,omitempty"`
            }

            // UpdateTagAttributesNotFoundResponse ...
            type UpdateTagAttributesNotFoundResponse struct {
            Data *Error `json:"data,omitempty"`
            }

            // UpdateTagAttributesUnauthorizedResponse ...
            type UpdateTagAttributesUnauthorizedResponse struct {
            Data *Error `json:"data,omitempty"`
            }

            // UpdateTagMetadataBadRequestResponse ...
            type UpdateTagMetadataBadRequestResponse struct {
            Data *Error `json:"data,omitempty"`
            }

            // UpdateTagMetadataNotFoundResponse ...
            type UpdateTagMetadataNotFoundResponse struct {
            Data *Error `json:"data,omitempty"`
            }

            // UpdateTagMetadataUnauthorizedResponse ...
            type UpdateTagMetadataUnauthorizedResponse struct {
            Data *Error `json:"data,omitempty"`
            }

            // UploadBlobContentBadRequestResponse ...
            type UploadBlobContentBadRequestResponse struct {
            Data *Error `json:"data,omitempty"`
            }

            // UploadBlobContentNotFoundResponse ...
            type UploadBlobContentNotFoundResponse struct {
            Data *Error `json:"data,omitempty"`
            }

            // UploadBlobContentUnauthorizedResponse ...
            type UploadBlobContentUnauthorizedResponse struct {
            Data *Error `json:"data,omitempty"`
            }

            // UploadManifestBadRequestResponse ...
            type UploadManifestBadRequestResponse struct {
            Data *Error `json:"data,omitempty"`
            }

            // UploadManifestUnauthorizedResponse ...
            type UploadManifestUnauthorizedResponse struct {
            Data *Error `json:"data,omitempty"`
            }

